version: "2"
services:
  web:
    build: .
    depends_on:
    - mongo
    labels:
        - "traefik.port=8080"
        - "traefik.frontend.rule=Host:fingerprint.idocker.hacking-lab.com"
        - "traefik.protocol=http"

  mongo:
    image: mongo
    volumes:
    - ./db:/data/db


